
scbWB='';
scbVZ='08028';
scbSPL='NNNN';
scbMM=(scbSPL.length>0?scbSPL.charAt(0):'N');
scbMSV=(scbSPL.length>1?scbSPL.charAt(1):'N');
scbVC=(scbSPL.length>2?scbSPL.charAt(2):'N');
scbIP=(scbSPL.length>3?scbSPL.charAt(3):'N');
scbPP='undecided';
scbVAS='N';
scbFS='N';
scbFSW='N';
scbVHM='';
scbHTP='';
scbVHS='';
scbbUP='Y';
scbAcct='primary';
scbAdm='N';
scbUP='UUEUUUU';
if(scbUP==''||scbUP.length<7){scbUP='UUUUUUU';}
scbUP1=scbUP.charAt(0);scbUP2=scbUP.charAt(1);scbUP3=scbUP.charAt(2);scbUP4=scbUP.charAt(3);scbUP5=scbUP.charAt(4);scbUP6=scbUP.charAt(5);scbUP7=scbUP.charAt(6);
scbfyhREC=true;
